Get http://localhost:3000/api/auth


###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username" : "ahmed",
    "email" : "ahmed@gmail.com",
    "password": "123456"
}

### 
POST http://localhost:3000/api/auth/login 
Content-Type: application/json

{
    "email" : "ahmed@gmail.com",
    "password": "123456"
}

###set avatar
POST http://localhost:3000/api/auth/setAvatar/659863004a08cf938ae8b95c
Content-Type: application/json

{
    "avatar" : ""
}

### get user by id
GET http://localhost:3000/api/auth/allUsers/659873bea1331a04dd331148


###add message
POST http://localhost:3000/api/messages/add-message
Content-Type: application/json

{
    "from" : "659977b9b82ee0749baf015f",
    "to" : "659977d7b82ee0749baf0166",
    "message" : "hi"
}


### get all users
GET http://localhost:3000/api/auth/allUsers