Get http://localhost:3000/api/auth


###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username" : "aaaaaaa",
    "email" : "ahmed1@gmail.com",
    "password": "123456"
}